### Create a new User signup

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Sign in a User

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Getting a User with id
GET http://localhost:3000/auth/whoami

### Signing out a User
POST http://localhost:3000/auth/signout

### Getting a User with email
GET http://localhost:3000/auth?email=someemail@email.com

### Deleting a User
DELETE http://localhost:3000/auth/4

### Updating a User
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "email": "changed@email.com"
}

# ### Setting a color
# GET http://localhost:3000/auth/colors/red

# ### Getting all colors
# GET http://localhost:3000/auth/colors
